# Data Understanding (CRISP-DM) - Olist
目的：依 CRISP-DM 的 Data Understanding 四個任務 ，建立可重現的資料理解流程。
1. Collect Initial Data  
2. Describe Data
3. Explore Data
4. Verify Data Quality

## 0. Setup

- 建立 MySQL 連線
- 載入分析所需套件

In [8]:
import sqlalchemy as sa
import pandas as pd

In [9]:
engine = sa.create_engine("mysql+pymysql://root:a24967679@localhost:3306/olist_raw")
# 建立資料庫引擎物件(連結到資料庫的統一路口)
conn = engine.connect() # 開新連線

## 1. Collect Initial Data 

目的：
- 確認已成功將所有原始 CSV 匯入 MySQL `raw_olist` schema
- 盤點目前可用資料表與 row 數

In [13]:
RAW_TABLES = [
    "olist_customers_dataset",
    "olist_geolocation_dataset",
    "olist_order_items_dataset",
    "olist_order_payments_dataset",
    "olist_order_reviews_dataset",
    "olist_orders_dataset",
    "olist_products_dataset",
    "olist_sellers_dataset",
    "product_category_name_translation",
]

query_raw_tables = f"""
SELECT 
    TABLE_NAME AS table_name,
    TABLE_ROWS AS table_rows
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'olist_raw' # 重定義的table list 去找資料表
  AND TABLE_NAME IN ({",".join("'" + t + "'" for t in RAW_TABLES)}) # 把串接表的列表的前後加上" " 
ORDER BY TABLE_NAME;
"""
df_tables = pd.read_sql(query_raw_tables, conn)

## 2. Table-level Summary  
* 2.1 Table基本資訊
* 2.2 Column說明
* 2.3 粒度
* 2.4 時間範圍
* 2.5 梳理PK / FK

### 2.1 Table基本資訊

In [15]:
df_tables

                          table_name  table_rows
0            olist_customers_dataset       98955
1          olist_geolocation_dataset      989712
2          olist_order_items_dataset      111391
3       olist_order_payments_dataset      103632
4        olist_order_reviews_dataset       97833
5               olist_orders_dataset       95378
6             olist_products_dataset       32970
7              olist_sellers_dataset        3095
8  product_category_name_translation          71

### 分析結果  
1. 顧客表：約有9萬筆
2. 地理表：約有98萬筆
3. 訂單明細表：約有11萬筆
4. 付款表：約有10萬筆
5. 評論表：約有9萬筆
6. 訂單表：約有9萬筆
7. 商品表：約有3萬筆
8. 賣家表：約有3000筆
9. 商品翻譯表：約有71筆

### 2.2 Column說明

In [22]:
query_cols = """
SELECT 
    TABLE_NAME      AS table_name,
    COLUMN_NAME     AS column_name,
    ORDINAL_POSITION AS column_position,
    DATA_TYPE       AS data_type,
    CHARACTER_MAXIMUM_LENGTH AS char_max_length,
    NUMERIC_PRECISION       AS num_precision,
    NUMERIC_SCALE           AS num_scale,
    IS_NULLABLE     AS is_nullable,
    COLUMN_KEY      AS column_key,
    COLUMN_DEFAULT  AS column_default,
    EXTRA           AS extra
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'olist_raw'
ORDER BY TABLE_NAME, ORDINAL_POSITION;
"""

df_cols = pd.read_sql(query_cols, conn)
df_cols.head(100)

,table_name,column_name,column_position,data_type,char_max_length,num_precision,num_scale,is_nullable,column_key,column_default,extra
0,olist_customers_dataset,customer_id,1,char,32.0,NaN,NaN,NO,PRI,None,
1,olist_customers_dataset,customer_unique_id,2,char,32.0,NaN,NaN,NO,,None,
2,olist_customers_dataset,customer_zip_code_prefix,3,int,NaN,10.0,0.0,NO,,None,
3,olist_customers_dataset,customer_city,4,varchar,100.0,NaN,NaN,NO,,None,
4,olist_customers_dataset,customer_state,5,char,2.0,NaN,NaN,NO,,None,
5,olist_geolocation_dataset,geolocation_zip_code_prefix,1,text,65535.0,NaN,NaN,YES,,None,
6,olist_geolocation_dataset,geolocation_lat,2,text,65535.0,NaN,NaN,YES,,None,
7,olist_geolocation_dataset,geolocation_lng,3,text,65535.0,NaN,NaN,YES,,None,
8,olist_geolocation_dataset,geolocation_city,4,text,65535.0,NaN,NaN,YES,,None,
9,olist_geolocation_dataset,geolocation_state,5,text,65535.0,NaN,NaN,YES,,None,
10,olist_order_items_dataset,order_id,1,text,65535.0,NaN,NaN,YES,,None,
11,olist_order_items_dataset,order_item_id,2,text,65535.0,NaN,NaN,YES,,None,
12,olist_order_items_dataset,product_id,3,text,65535.0,NaN,NaN,YES,,None,
13,olist_order_items_dataset,seller_id,4,text,65535.0,NaN,NaN,YES,,None,
14,olist_order_items_dataset,shipping_limit_date,5,text,65535.0,NaN,NaN,YES,,None,
15,olist_order_items_dataset,price,6,text,65535.0,NaN,NaN,YES,,None,
16,olist_order_items_dataset,freight_value,7,text,65535.0,NaN,NaN,YES,,None,
17,olist_order_payments_dataset,order_id,1,text,65535.0,NaN,NaN,YES,,None,
18,olist_order_payments_dataset,payment_sequential,2,text,65535.0,NaN,NaN,YES,,None,
19,olist_order_payments_dataset,payment_type,3,text,65535.0,NaN,NaN,YES,,None,
20,olist_order_payments_dataset,payment_installments,4,text,65535.0,NaN,NaN,YES,,None,
21,olist_order_payments_dataset,payment_value,5,text,65535.0,NaN,NaN,YES,,None,
22,olist_order_reviews_dataset,review_id,1,text,65535.0,NaN,NaN,YES,,None,
23,olist_order_reviews_dataset,order_id,2,text,65535.0,NaN,NaN,YES,,None,
24,olist_order_reviews_dataset,review_score,3,text,65535.0,NaN,NaN,YES,,None,
25,olist_order_reviews_dataset,review_comment_title,4,text,65535.0,NaN,NaN,YES,,None,
26,olist_order_reviews_dataset,review_comment_message,5,text,65535.0,NaN,NaN,YES,,None,
27,olist_order_reviews_dataset,review_creation_date,6,text,65535.0,NaN,NaN,YES,,None,
28,olist_order_reviews_dataset,review_answer_timestamp,7,text,65535.0,NaN,NaN,YES,,None,
29,olist_orders_dataset,order_id,1,char,32.0,NaN,NaN,NO,PRI,None,
30,olist_orders_dataset,customer_id,2,char,32.0,NaN,NaN,NO,MUL,None,
31,olist_orders_dataset,order_status,3,text,65535.0,NaN,NaN,YES,,None,
32,olist_orders_dataset,order_purchase_timestamp,4,text,65535.0,NaN,NaN,YES,,None,
33,olist_orders_dataset,order_approved_at,5,text,65535.0,NaN,NaN,YES,,None,
34,olist_orders_dataset,order_delivered_carrier_date,6,text,65535.0,NaN,NaN,YES,,None,
35,olist_orders_dataset,order_delivered_customer_date,7,text,65535.0,NaN,NaN,YES,,None,
36,olist_orders_dataset,order_estimated_delivery_date,8,text,65535.0,NaN,NaN,YES,,None,
37,olist_products_dataset,product_id,1,text,65535.0,NaN,NaN,YES,,None,
38,olist_products_dataset,product_category_name,2,text,65535.0,NaN,NaN,YES,,None,
39,olist_products_dataset,product_name_lenght,3,text,65535.0,NaN,NaN,YES,,None,
40,olist_products_dataset,product_description_lenght,4,text,65535.0,NaN,NaN,YES,,None,
41,olist_products_dataset,product_photos_qty,5,text,65535.0,NaN,NaN,YES,,None,
42,olist_products_dataset,product_weight_g,6,text,65535.0,NaN,NaN,YES,,None,
43,olist_products_dataset,product_length_cm,7,text,65535.0,NaN,NaN,YES,,None,
44,olist_products_dataset,product_height_cm,8,text,65535.0,NaN,NaN,YES,,None,
45,olist_products_dataset,product_width_cm,9,text,65535.0,NaN,NaN,YES,,None,
46,olist_sellers_dataset,seller_id,1,char,32.0,NaN,NaN,NO,PRI,None,
47,olist_sellers_dataset,seller_zip_code_prefix,2,int,NaN,10.0,0.0,NO,MUL,None,
48,olist_sellers_dataset,seller_city,3,varchar,100.0,NaN,NaN,NO,,None,
49,olist_sellers_dataset,seller_state,4,char,2.0,NaN,NaN,NO,MUL,None,
50,product_category_name_translation,product_category_name,1,text,65535.0,NaN,NaN,YES,,None,
51,product_category_name_translation,product_category_name_english,2,text,65535.0,NaN,NaN,YES,,None,

### 2.3粒度

In [18]:
grain_map = {
    "olist_customers_dataset": "每 row = 一個 customer_unique_id",
    "olist_geolocation_dataset": "每 row = 一個 zip_code_prefix + 經緯度點",
    "olist_order_items_dataset": "每 row = 一筆訂單中的一個商品明細",
    "olist_order_payments_dataset": "每 row = 一筆訂單的一次付款紀錄",
    "olist_order_reviews_dataset": "每 row = 一筆訂單的一則評論",
    "olist_orders_dataset": "每 row = 一筆訂單",
    "olist_products_dataset": "每 row = 一個 product_id",
    "olist_sellers_dataset": "每 row = 一個 seller_id",
    "product_category_name_translation": "每 row = 一個商品品類的葡文/英文對照"
}

df_tables["grain_desc"] = df_tables["table_name"].map(grain_map)
df_tables

,table_name,table_rows,grain_desc
0,olist_customers_dataset,98955,每 row = 一個 customer_unique_id
1,olist_geolocation_dataset,989712,每 row = 一個 zip_code_prefix + 經緯度點
2,olist_order_items_dataset,111391,每 row = 一筆訂單中的一個商品明細
3,olist_order_payments_dataset,103632,每 row = 一筆訂單的一次付款紀錄
4,olist_order_reviews_dataset,97833,每 row = 一筆訂單的一則評論
5,olist_orders_dataset,95378,每 row = 一筆訂單
6,olist_products_dataset,32970,每 row = 一個 product_id
7,olist_sellers_dataset,3095,每 row = 一個 seller_id
8,product_category_name_translation,71,每 row = 一個商品品類的葡文/英文對照

### 2.4 時間範圍

In [19]:
DATE_COLUMNS = {
    "olist_orders_dataset": "order_purchase_timestamp",
    "olist_order_reviews_dataset": "review_creation_date",
    "olist_order_items_dataset": "shipping_limit_date",
    # 若有需要可再加，例如 olist_geolocation_dataset 沒日期就不用
}

def get_date_range(table, date_column):
    q = f"""
    SELECT 
        MIN({date_column}) AS min_date,
        MAX({date_column}) AS max_date
    FROM olist_raw.{table};
    """
    return pd.read_sql(q, conn).assign(
        table_name=table,
        date_column=date_column
    )

df_dates = pd.concat(
    [get_date_range(t, c) for t, c in DATE_COLUMNS.items()],
    ignore_index=True
)
df_dates

,min_date,max_date,table_name,date_column
0,2016/10/10 0:01,2018/9/6 18:45,olist_orders_dataset,order_purchase_timestamp
1,2016/10/15 0:00,2018/8/9 0:00,olist_order_reviews_dataset,review_creation_date
2,2016/10/10 11:43,2020/4/9 22:35,olist_order_items_dataset,shipping_limit_date